services:
  # 1. RustFS (Object Storage)
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped
    # IMPORTANTE: Eliminado 'network_mode: bridge' para permitir DNS custom
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - TZ=${TZ}
      - MINIO_ROOT_USER=${RUSTFS_USER}
      - MINIO_ROOT_PASSWORD=${RUSTFS_PASSWORD}
      - RUSTFS_ACCESS_KEY=${RUSTFS_USER}
      - RUSTFS_SECRET_KEY=${RUSTFS_PASSWORD}
      - RUSTFS_ERASURE_SET_DRIVE_COUNT=1
    volumes:
      - rustfs_data:/data
    networks:
      - airflow_shared

  # 2. PostgreSQL (Metadata Database)
  postgres:
    image: postgres:15-alpine
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "30432:5432"
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - airflow_shared

  # 3. Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "9443:9443"
      - "9002:9000"
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - airflow_shared

networks:
  airflow_shared:
    name: airflow_886f83_airflow # Conectamos a la red existente de tu Airflow
    external: true

volumes:
  rustfs_data:
  pg_data:
  portainer_data:
